### ISSUE TITLE
A ValueError reported when running runner_eval.py

### ISSUE THREAD

**Issue by zachzhuu** [zdchan/artigrasp#8]
Thanks for sharing your excellent projects and codes. I finished the installation with the guidance of the `Installation.md`, but an error occurred when I ran:
```
$ python raisimGymTorch/env/envs/general_two/runner_eval.py
```
output of the terminal:
```
Configuration file: "cfg_reg.yaml"
Experiment name: "general_two"
notebook
arti label num:  14
grasp label num:  19
 
box
arti label num:  19
grasp label num:  33
 
laptop
arti label num:  19
grasp label num:  29
 
waffleiron
arti label num:  33
grasp label num:  22
 
mixer
arti label num:  41
grasp label num:  64
 
ketchup
arti label num:  20
grasp label num:  59
 
phone
arti label num:  26
grasp label num:  64
 
capsulemachine
arti label num:  36
grasp label num:  49
 
espressomachine
arti label num:  63
grasp label num:  21
 
microwave
arti label num:  10
grasp label num:  22
 
seq_num:  6
seq_name:  waffleiron_use_02
init_frame:  497
grasp_frame:  509
kind:  right_arti
Traceback (most recent call last):
  File "raisimGymTorch/env/envs/general_two/runner_eval.py", line 101, in <module>
    processed_data, obj_list, left_kind_list, right_kind_list = label_gen_final.pose_gen(shuffle_label, num_repeats, False)
  File "/home/zachzhu/projects/artigrasp/raisimGymTorch/raisimGymTorch/helper/label_gen_final.py", line 764, in pose_gen
    gt_rel_rot = rotations.euler2mat([0, 0, rel_angle])
  File "/home/zachzhu/projects/artigrasp/raisimGymTorch/raisimGymTorch/helper/rotations.py", line 184, in euler2mat
    euler = np.asarray(euler, dtype=np.float64)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```
Also, when I opened `raisimUnity/linux/raisimUnity.x86_64`, the interface was all black, I thought it might crash...
Thanks again for your sharing. I will appreciate it if you can help.

**Comment by zdchan** [comment]
Thanks for the interest in our work! I am not quite sure what caused the problem as it works from my side. Could you try to replace your numpy version to 1.23.1? Maybe this can help

**Comment by zachzhuu** [comment]
> Thanks for the interest in our work! I am not quite sure what caused the problem as it works from my side. Could you try to replace your numpy version to 1.23.1? Maybe this can help

Changing the numpy version does work. Thank you for your help!
